Error Connecting: http://172.217.16.3:443 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 2021-09-23 06:27:50.366022
Error Connecting: http://172.217.16.3:443 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 2021-09-23 06:35:12.940788
Error Connecting: http://172.217.16.3:443 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 2021-09-23 06:37:28.500524
Error Connecting: http://172.217.16.3:443 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 2021-09-23 06:39:21.662043
Error Connecting: http://172.217.16.3:443 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 2021-09-23 06:40:12.393007
Error Connecting: http://172.217.16.3:443 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 2021-09-23 06:47:10.889726
Error Connecting: http://172.217.16.3:443 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 2021-09-23 06:47:31.473095
Error Connecting: http://172.217.16.3:443 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 2021-09-23 06:48:09.063169
Error Connecting: http://142.250.203.206:80 HTTPConnectionPool(host='142.250.203.206', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2172616be0>: Failed to establish a new connection: [Errno 101] Network is unreachable')) 2021-09-23 06:48:09.063169
Error Connecting: http://142.250.203.132:80 HTTPConnectionPool(host='142.250.203.132', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2173130df0>: Failed to establish a new connection: [Errno 101] Network is unreachable')) 2021-09-23 06:48:09.063169
Error Connecting: http://172.217.16.3:443 HTTPConnectionPool(host='172.217.16.3', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f21725d1580>: Failed to establish a new connection: [Errno 101] Network is unreachable')) 2021-09-23 06:48:09.063169
Error Connecting: http://142.250.203.206:80 HTTPConnectionPool(host='142.250.203.206', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eb8d5e640>: Failed to establish a new connection: [Errno 101] Network is unreachable')) 2021-09-23 06:49:20.040567
Error Connecting: http://142.250.203.132:80 HTTPConnectionPool(host='142.250.203.132', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eb8d5eac0>: Failed to establish a new connection: [Errno 101] Network is unreachable')) 2021-09-23 06:49:20.040567
Error Connecting: http://172.217.16.3:443 HTTPConnectionPool(host='172.217.16.3', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eb8d5eaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable')) 2021-09-23 06:49:20.040567
